server:
  port: 8070

spring:
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Bogdan
    username: postgres
    password: 07072003Bogdan
  jpa:
    open-in-view: true
    show-sql: false
    generate-ddl: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

  servlet:
    multipart:
      max-file-size: 10MB        # Максимальный размер загружаемого файла
      max-request-size: 10MB     # Максимальный размер всего запроса
